
package com.ifobia.main;
import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.extras.FlatAnimatedLafChange;
import com.ifobia.form.FormLogin;
import com.ifobia.entity.user;
import java.awt.Component;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author Andhika Eka Pratama
 */
public class FormMenuUtama extends javax.swing.JFrame {
    private final FormLogin formLogin;
    private static FormMenuUtama app;
    private final Main mainForm;
    private static user loggedInUser;
    
    // Method baru untuk MENYIMPAN user (INI YANG HILANG)
    public static void setLoggedInUser(user user) {
        loggedInUser = user;
    }

    // Method baru untuk MENGAMBIL user
    public static user getLoggedInUser() {
        return loggedInUser;
    }
    
     public static String getUserRole() {
    if (loggedInUser != null) {
        return loggedInUser.getRole();
    }
    return "GUEST"; // Jika tidak ada user, kembalikan GUEST
    }

    public static boolean isAdmin() {
        // 1. Cek dulu apakah ada user yang login
        if (loggedInUser == null) {
            return false;
        }

        // 2. Ambil role-nya (String) dan bandingkan dengan "PJ"
        return loggedInUser.getRole().equals("pj");
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormMenuUtama.class.getName());

    /**
     * Creates new form FormMenuUtama
     */
    public FormMenuUtama() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setIconImage(new ImageIcon(getClass().getResource("/com/ifobia/icon/logo.png")).getImage());
        formLogin = new FormLogin();
        mainForm = new Main();
        setContentPane(formLogin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //role



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLaf.registerCustomDefaultsSource("com.ifobia.theme");
       FlatLightLaf.setup();
        //FlatDarculaLaf.setup();

     java.awt.EventQueue.invokeLater(() -> {
         app = new FormMenuUtama();
         app.setVisible(true);

        });
    }
    
    public static void showForm(Component component) {
    component.applyComponentOrientation(app.getComponentOrientation());
    app.mainForm.showForm(component);
    }
    
    public static void login() {
    FlatAnimatedLafChange.showSnapshot();
    app.setContentPane(app.mainForm);
    app.mainForm.applyComponentOrientation(app.getComponentOrientation());
    app.mainForm.refreshMenu();
    setSelectedMenu(0, 0);
    app.mainForm.hideMenu();
    SwingUtilities.updateComponentTreeUI(app.mainForm);
    FlatAnimatedLafChange.hideSnapshotWithAnimation();
    }
    public static void setSelectedMenu(int index, int subMenu) {
    app.mainForm.setSelectedMenu(index, subMenu);
    }
    
    public static void logout() {
    FlatAnimatedLafChange.showSnapshot();
    app.setContentPane(app.formLogin);
    app.formLogin.applyComponentOrientation(app.getComponentOrientation());
    SwingUtilities.updateComponentTreeUI(app.formLogin);
    FlatAnimatedLafChange.hideSnapshotWithAnimation();
    loggedInUser = null; // Ini untuk membersihkan data user saat logout
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
