/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ifobia.form;

import com.formdev.flatlaf.FlatClientProperties;
import com.ifobia.entity_dao.tugasDAO;
import com.ifobia.entity.mataKuliah;
import com.ifobia.entity.tugas; 
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane; 
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andhika Eka Pratama
 */
public class FormKelolaTugas extends javax.swing.JPanel {
    
private tugasDAO dao;
    private DefaultComboBoxModel<mataKuliah> matkulComboBoxModel;
    private DefaultTableModel tableModel; 
    
    public FormKelolaTugas() {
        initComponents();
        
        
        
        jButton1.putClientProperty(FlatClientProperties.STYLE, 
        "background:$Button.custom.background");
        txtJudul.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Contoh: Pertemuan 1 - PBO Asdos");
        txtDeadline.putClientProperty(com.formdev.flatlaf.FlatClientProperties.PLACEHOLDER_TEXT, "YYYY-MM-DD");
        
        
        
        // --- INISIALISASI ---
        dao = new tugasDAO(); 
        tableModel = (DefaultTableModel) jTable1.getModel();
        matkulComboBoxModel = new DefaultComboBoxModel<>();
        jComboBoxMatkul.setModel(matkulComboBoxModel);
        
        loadDataMataKuliah();
        loadDataTugasAdmin(); 
    }
    
    /**
     * Method 1: Memuat mata kuliah ke ComboBox
     */
    private void loadDataMataKuliah() {
        matkulComboBoxModel.removeAllElements(); // Kosongkan dulu
        List<mataKuliah> daftarMatkul = dao.getAllMataKuliah();
        for (mataKuliah matkul : daftarMatkul) {
            matkulComboBoxModel.addElement(matkul);
        }
    }
    
    /**
     * Method 2: Memuat data tugas (VERSI ADMIN)
     */
    private void loadDataTugasAdmin() {
        // Atur nama kolom (Hapus "Status")
        tableModel.setColumnIdentifiers(new Object[]{
            "ID", "Mata Kuliah", "Judul", "Deskripsi", "Deadline"
        });
        
        tableModel.setRowCount(0); 
        List<tugas> daftarTugas = dao.getAllTugasForAdmin();
        
        for (tugas t : daftarTugas) {
            tableModel.addRow(new Object[]{
                t.getId_tugas(),
                t.getNama_mk(),
                t.getJudul(),
                t.getDeskripsi(),
                t.getDeadline()
                // Tidak ada t.getIsSelesai()
            });
        }
        
        // Sembunyikan kolom ID (Opsional, tapi rapi)
        jTable1.getColumnModel().getColumn(0).setMinWidth(0);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(0).setWidth(0);
    }
    
    /**
     * Method 3: Mengosongkan form input
     */
    private void clearForm() {
        jComboBoxMatkul.setSelectedIndex(0);
        txtJudul.setText(""); // Judul
        txtDeskripsi.setText(""); // Deskripsi
        txtDeadline.setText(""); // Deadline
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblInfoMatkul1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtJudul = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDeadline = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDeskripsi = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxMatkul = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        setLayout(new java.awt.GridBagLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Judul", "Deskripsi", "Deadline"
            }
        ));
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 908;
        gridBagConstraints.ipady = 366;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(25, 51, 0, 0);
        add(jScrollPane1, gridBagConstraints);

        lblInfoMatkul1.setFont(new java.awt.Font("Leelawadee", 1, 36)); // NOI18N
        lblInfoMatkul1.setText("Kelola Tugas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(45, 52, 0, 0);
        add(lblInfoMatkul1, gridBagConstraints);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102)));

        jLabel2.setFont(new java.awt.Font("Leelawadee", 1, 12)); // NOI18N
        jLabel2.setText("Judul");

        jLabel3.setFont(new java.awt.Font("Leelawadee", 1, 12)); // NOI18N
        jLabel3.setText("Deadline");

        txtDeskripsi.setColumns(20);
        txtDeskripsi.setRows(5);
        jScrollPane2.setViewportView(txtDeskripsi);

        jLabel4.setFont(new java.awt.Font("Leelawadee", 1, 12)); // NOI18N
        jLabel4.setText("Deskripsi Tugas");

        jButton1.setBackground(new java.awt.Color(13, 71, 161));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Tambah Tugas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Leelawadee", 1, 12)); // NOI18N
        jLabel5.setText("Mata Kuliah");

        jLabel1.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabel1.setText("Bagikan Tugas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jComboBoxMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(txtJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(txtDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addGap(6, 6, 6)
                .addComponent(jComboBoxMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addComponent(txtJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel3)
                .addGap(6, 6, 6)
                .addComponent(txtDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel4)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(25, 18, 0, 17);
        add(jPanel2, gridBagConstraints);

        jButton2.setBackground(new java.awt.Color(204, 0, 51));
        jButton2.setFont(new java.awt.Font("Leelawadee", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Hapus Tugas");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 51, 25, 0);
        add(jButton2, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Leelawadee", 2, 12)); // NOI18N
        jLabel6.setText("**Klik Judul  Tugas untuk menghapus");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 270;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 51, 0, 0);
        add(jLabel6, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try {
            // 1. Ambil data dari form
            mataKuliah matkul = (mataKuliah) jComboBoxMatkul.getSelectedItem();
            if (matkul == null) {
                JOptionPane.showMessageDialog(this, "Pilih mata kuliah dulu!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            String kodeMk = matkul.getKode_mk();
            String judul = txtJudul.getText();
            String deskripsi = txtDeskripsi.getText();
            String deadline = txtDeadline.getText(); // "YYYY-MM-DD"
            
            if (judul.isEmpty() || deadline.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Judul dan Deadline tidak boleh kosong!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // 2. Buat objek 'tugas' baru (pakai konstruktor 1)
            tugas t = new tugas(kodeMk, judul, deskripsi, deadline);
            
            // 3. Simpan ke database
            boolean sukses = dao.tambahTugas(t);
            
            // 4. Update UI
            if (sukses) {
                JOptionPane.showMessageDialog(this, "Tugas berhasil ditambahkan dan didistribusikan ke mahasiswa!");
                loadDataTugasAdmin(); // Refresh tabel ADMIN
                clearForm();     // Kosongkan form
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menambah tugas.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Terjadi error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    
    // 1. Cek apakah ada baris yang dipilih
    int selectedRow = jTable1.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Pilih baris tugas yang ingin dihapus.");
        return;
    }
    
    // 2. Ambil ID tugas dari kolom tersembunyi (Kolom 0)
    int modelRow = jTable1.convertRowIndexToModel(selectedRow);
    int id_tugas = (int) tableModel.getValueAt(modelRow, 0); // Asumsi kolom 0 adalah ID
    String judul_tugas = tableModel.getValueAt(modelRow, 2).toString(); // Asumsi kolom 2 adalah Judul
    
    // 3. Konfirmasi penghapusan
    int confirm = JOptionPane.showConfirmDialog(this, 
            "Yakin ingin menghapus tugas:\n" + judul_tugas + "?", 
            "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
            
    if (confirm == JOptionPane.YES_OPTION) {
        
        // 4. Panggil DAO untuk menghapus
        tugasDAO dao = new tugasDAO(); 
        if (dao.hapusTugas(id_tugas)) {
            JOptionPane.showMessageDialog(this, "Tugas berhasil dihapus!");
            
            // 5. Refresh tabel
            loadDataTugasAdmin(); 
        } else {
            JOptionPane.showMessageDialog(this, "Gagal menghapus tugas.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    dao.getAllTugasForAdmin();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<mataKuliah> jComboBoxMatkul;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblInfoMatkul1;
    private javax.swing.JTextField txtDeadline;
    private javax.swing.JTextArea txtDeskripsi;
    private javax.swing.JTextField txtJudul;
    // End of variables declaration//GEN-END:variables

}
