/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ifobia.form;


import com.formdev.flatlaf.FlatClientProperties;
import com.ifobia.entity_dao.tugasDAO;
import com.ifobia.entity.tugas;
import com.ifobia.entity.user; 
import com.ifobia.main.FormMenuUtama; 
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andhika Eka Pratama
 */
public class FormTugas extends javax.swing.JPanel {
    
    private tugasDAO dao;
    private DefaultTableModel tableModel;
    private user userLogin;

    /**
     * Creates new form FormTugas
     */
    public FormTugas() {
        initComponents();
        //button light&dark mode
        btnTugas.putClientProperty(FlatClientProperties.STYLE, 
        "background:$Button.custom.background");
        btnTugas.setText("Tandai Selesai");
        
        dao = new tugasDAO();
        tableModel = (DefaultTableModel) jTable1.getModel();
        
        // 2. AMBIL USER YANG LOGIN (Ini Kuncinya!)
        this.userLogin = FormMenuUtama.getLoggedInUser(); 
        
        // 3. Cek apakah user ketemu?
        if (this.userLogin == null) {
            // Kalau null, berarti FormLogin belum nyimpen data (Login ulang gih)
            System.out.println("WARNING: User login tidak ditemukan / NULL.");
            return; 
        }
        
        // 4. Kalau user aman, PANGGIL DATANYA!
        loadDataTugas();
        
        txtCari.putClientProperty(com.formdev.flatlaf.FlatClientProperties.PLACEHOLDER_TEXT, "Cari Judul / Matkul...");
        txtCari.putClientProperty(com.formdev.flatlaf.FlatClientProperties.STYLE, "arc:10"); // Biar agak bulat
        
    }
    
    /**
     * METHOD UTAMA: Mengambil tugas dari Database khusus buat User ini
     */
   // FormTugas.java

    private void loadDataTugas() {
        // 1. Definisikan kolom tabel
        tableModel.setColumnIdentifiers(new Object[]{"ID", "Mata Kuliah", "Judul Tugas", "Deadline", "Status"});
        tableModel.setRowCount(0); // Kosongkan data lama

        if (this.userLogin == null) return; // Guard clause jika user belum login

        // 2. Ambil data dari DAO
        List<tugas> list = dao.getAllTugas(this.userLogin.getId_user());

        // 3. Isi tabel
        for (tugas t : list) {
            String statusDB = t.getIsSelesai();
            // Konversi status dari DB ("Selesai" atau "Belum") ke teks tampilan
            String statusTampilan = (statusDB != null && statusDB.equalsIgnoreCase("Selesai")) ? "Sudah Selesai" : "Belum Selesai";
            
            tableModel.addRow(new Object[]{
                t.getId_tugas(), 
                t.getNama_mk(),
                t.getJudul(),
                t.getDeadline(),
                statusTampilan // <-- Gunakan teks tampilan
            });
        }

        // 4. Sembunyikan kolom ID (Jika diinginkan)
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(0);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
            jTable1.getColumnModel().getColumn(0).setWidth(0);
        }
    }

    
    
    private void tampilkanPencarian(String key) {
    tableModel.setRowCount(0); // Bersihkan tabel
    
    // Pengecekan keamanan
    if (userLogin == null) {
        JOptionPane.showMessageDialog(this, "Error: Data user tidak ditemukan. Silahkan Login Ulang.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    // Panggil method DAO yang baru
    List<tugas> daftarTugas = dao.searchTugas(key, userLogin.getId_user());

    int no = 1;
    for (tugas t : daftarTugas) {
        String statusDB = t.getIsSelesai();
        // Konversi status dari DB ("Selesai" atau "Belum") ke teks tampilan
        String statusTampilan = (statusDB != null && statusDB.equalsIgnoreCase("Selesai")) ? "Sudah Selesai" : "Belum Selesai";
        // Isi tabel dengan data yang sudah difilter
      tableModel.addRow(new Object[] {
            t.getId_tugas(), 
            t.getNama_mk(),
            t.getJudul(),
            t.getDeadline(),
            statusTampilan 
        });
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnTugas = new javax.swing.JButton();
        lblInfoMatkul1 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mata Kuliah", "Judul", "Deskripsi", "Deadline", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 115, 1022, 320));

        btnTugas.setBackground(new java.awt.Color(13, 71, 161));
        btnTugas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTugas.setForeground(new java.awt.Color(255, 255, 255));
        btnTugas.setText("Tandai Selesai");
        btnTugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTugasActionPerformed(evt);
            }
        });
        add(btnTugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 453, -1, 33));

        lblInfoMatkul1.setFont(new java.awt.Font("Leelawadee", 1, 36)); // NOI18N
        lblInfoMatkul1.setText("Tugas");
        add(lblInfoMatkul1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 51, -1, -1));

        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });
        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });
        add(txtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(731, 81, 269, -1));

        jButton2.setBackground(new java.awt.Color(0, 51, 153));
        jButton2.setFont(new java.awt.Font("Leelawadee", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1006, 82, 76, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnTugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTugasActionPerformed

    // 1. Cek baris mana yang dipilih
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih tugas dulu!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // 2. Ambil ID Tugas, Judulnya, dan Status saat ini
        int id_tugas = (int) jTable1.getValueAt(selectedRow, 0);
        String judul = (String) jTable1.getValueAt(selectedRow, 2);
        String statusSaatIni = (String) jTable1.getValueAt(selectedRow, 4); // Ambil status dari kolom ke-4
        int id_user = userLogin.getId_user(); // ID User kita
        
        // 3. Validasi: Sudah Selesai
        if (statusSaatIni.equalsIgnoreCase("Sudah Selesai")) {
            JOptionPane.showMessageDialog(this, 
                    "Tugas '" + judul + "' sudah ditandai selesai.", 
                    "Informasi", 
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        // 4. Konfirmasi
        int confirm = JOptionPane.showConfirmDialog(this, 
                "Yakin tugas '" + judul + "' sudah selesai?", 
                "Konfirmasi", JOptionPane.YES_NO_OPTION);
                
        if (confirm == JOptionPane.YES_OPTION) {
            // 5. Suruh DAO update status jadi 'Selesai' (Sudah pakai UPSERT di DAO)
            if (dao.tandaiSelesai(id_user, id_tugas)) {
                JOptionPane.showMessageDialog(this, "Mantap! Tugas selesai.");
                
                // PERBAIKAN: Langsung update status di tabel (kolom 4) agar tetap tampil
                tableModel.setValueAt("Sudah Selesai", selectedRow, 4);
                
            } else {
                JOptionPane.showMessageDialog(this, "Gagal update status.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        
        dao.getAllTugas(this.userLogin.getId_user());
        
    }//GEN-LAST:event_btnTugasActionPerformed

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
                                            
    String key = txtCari.getText().trim();
    
    if (key.isEmpty()) {
        loadDataTugas(); // Kalau kosong, panggil method default untuk memuat semua tugas yang belum selesai
    } else {
        tampilkanPencarian(key); // Kalau ada isinya, panggil fungsi search
    }

    }//GEN-LAST:event_txtCariKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTugas;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblInfoMatkul1;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables
}
