/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ifobia.form;

import com.ifobia.entity_dao.pengumumanDAO;
import com.ifobia.entity.pengumuman;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andhika Eka Pratama
 */
public class FormPengumuman extends javax.swing.JPanel {

    /**
     * Creates new form FormPengumuman
     */
    public FormPengumuman() {
        initComponents();
        loadDataLengkap();
    }
    
    private void loadDataLengkap() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        // --- UBAH JADI 2 KOLOM SAJA ---
        model.setColumnIdentifiers(new Object[]{"Mata Kuliah", "Detail Pengumuman"});
        
        model.setRowCount(0); // Bersihkan tabel
        
        pengumumanDAO dao = new pengumumanDAO();
        List<pengumuman> list = dao.getPengumumanLengkap(); 
        
        for (pengumuman p : list) {
            
            // --- INI RAHASIANYA (FORMAT HTML DI DALAM SEL) ---
            // Kita gabung 3 elemen jadi satu string HTML
            String kontenSatuSel = "<html>" +
                                   "<b style='font-size:11px;'>" + p.getJudul() + "</b>" + // Judul TEBAL
                                   "<br>" + // Pindah baris
                                   p.getIsi() + // Isi Pengumuman
                                   "<br><br>" + // Jarak 2 baris biar rapi
                                   "<span style='color:gray; font-size:9px;'><i>" + p.getFooter() + "</i></span>" + // Footer kecil & miring
                                   "</html>";
            
            // Masukkan ke tabel (Cuma 2 kolom)
            model.addRow(new Object[]{
                p.getNamaMk(),      // Kolom 1: Matkul
                kontenSatuSel       // Kolom 2: Gabungan Semuanya
            });
        }
        
        // --- ATUR TAMPILAN TABEL BIAR CANTIK ---
        jTable1.setRowHeight(90); 
        
        // 2. Atur lebar kolom (Kolom Matkul kecil aja, Kolom Detail lebar)
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(150);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(200);
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblInfoMatkul1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        setLayout(new java.awt.GridBagLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mata kuliah", "Judul", "Isi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 838;
        gridBagConstraints.ipady = 174;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(12, 36, 44, 94);
        add(jScrollPane1, gridBagConstraints);

        lblInfoMatkul1.setFont(new java.awt.Font("Leelawadee", 1, 36)); // NOI18N
        lblInfoMatkul1.setText("Pengumuman");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(48, 36, 0, 0);
        add(lblInfoMatkul1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblInfoMatkul1;
    // End of variables declaration//GEN-END:variables
}
