/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ifobia.form;

// --- TAMBAHKAN INI ---
import com.ifobia.entity_dao.jadwalDAO;
import com.ifobia.entity_dao.pengumumanDAO;
import com.ifobia.entity_dao.tugasDAO;
import com.ifobia.entity.jadwal;
import com.ifobia.entity.pengumuman;
import com.ifobia.entity.tugas;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import com.ifobia.entity.user;
import com.ifobia.main.FormMenuUtama;
// ----------------------

/**
 *
 * @author Andhika Eka Pratama
 */
public class FormDashboard extends javax.swing.JPanel {

    private jadwalDAO dao;
    private DefaultTableModel tableModelDashboard;
    
    
    public FormDashboard() {
        initComponents();
        
        
        // --- TAMBAHKAN INI ---
        dao = new jadwalDAO();
        tableModelDashboard = (DefaultTableModel) jTable1.getModel();
        
        
        // Panggil 2 method baru di bawah
        sapaUser();
        loadDataJadwalDashboard();
        loadDataTugasDashboard();
        loadPengumumanSimple();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaPengumuman = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextAreaTugas = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        setLayout(new java.awt.GridBagLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(908, 517));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("DASHBOARD");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(43, 50, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Leelawadee", 1, 36)); // NOI18N
        jLabel2.setText("Dashboard");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Leelawadee", 1, 15)); // NOI18N
        jLabel3.setText("  Jadwal Kelas Minggu Ini   ");
        jLabel3.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 50, 0, 0);
        jPanel1.add(jLabel3, gridBagConstraints);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(204, 204, 204));
        jTable1.setRowHeight(23);
        jTable1.setShowGrid(true);
        jScrollPane2.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 796;
        gridBagConstraints.ipady = 196;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(11, 50, 0, 0);
        jPanel1.add(jScrollPane2, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Leelawadee", 1, 15)); // NOI18N
        jLabel4.setText("Pengumuman   ");
        jLabel4.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 50, 0, 0);
        jPanel1.add(jLabel4, gridBagConstraints);

        jTextAreaPengumuman.setEditable(false);
        jTextAreaPengumuman.setColumns(20);
        jTextAreaPengumuman.setRows(5);
        jScrollPane4.setViewportView(jTextAreaPengumuman);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 796;
        gridBagConstraints.ipady = 217;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(12, 50, 21, 0);
        jPanel1.add(jScrollPane4, gridBagConstraints);

        jTextAreaTugas.setEditable(false);
        jTextAreaTugas.setColumns(20);
        jTextAreaTugas.setRows(5);
        jScrollPane5.setViewportView(jTextAreaTugas);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 355;
        gridBagConstraints.ipady = 482;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(11, 18, 21, 35);
        jPanel1.add(jScrollPane5, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Leelawadee", 1, 15)); // NOI18N
        jLabel5.setText("Tugas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 18, 0, 0);
        jPanel1.add(jLabel5, gridBagConstraints);

        jScrollPane1.setViewportView(jPanel1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1174;
        gridBagConstraints.ipady = 528;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 6);
        add(jScrollPane1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextAreaPengumuman;
    private javax.swing.JTextArea jTextAreaTugas;
    // End of variables declaration//GEN-END:variables


//Method 1: Sapa user yang login 

    private void sapaUser() {
        try {
            user u = FormMenuUtama.getLoggedInUser();
            if (u != null) {
                jLabel1.setText("Hai, " + u.getNama() + "!");
            }
        } catch (Exception e) {
        }
    }

//Method 2: Memuat data jadwal ke tabel di Dashboard

    private void loadDataJadwalDashboard() {
        // Atur nama kolom tabel di Dashboard
        tableModelDashboard.setColumnIdentifiers(new Object[]{
            "Hari", "Waktu", "Mata Kuliah", "Dosen", "Ruangan"
        });

        tableModelDashboard.setRowCount(0); // Kosongkan tabel
        List<jadwal> daftarJadwal = dao.getAlljadwalForDashboard();

        for (jadwal jadwal : daftarJadwal) {
            Object[] row = {
                jadwal.getHari(),
                jadwal.getWaktu(), 
                jadwal.getNama_mk(),
                jadwal.getNama_dosen(),
                jadwal.getRuangan()
            };
            
            tableModelDashboard.addRow(row);
        }
    }
    
// Method 3: Memuat data tugas
    
    // FormDashboard.java

private void loadDataTugasDashboard() {
        
    user u = FormMenuUtama.getLoggedInUser();
    if (u == null) return; // Guard clause
    
    tugasDAO tDao = new tugasDAO();
    
    // Panggil method getAllTugas yang sudah diperbaiki
    List<tugas> list = tDao.getAllTugas(u.getId_user());
    
    StringBuilder sb = new StringBuilder();
    int no = 1;
    
    // Pastikan di class tugas.java ada method getDashboardText() yang memformat output.
    for (tugas t : list) {
        // Format: "1. [Nama MK] - [Judul Tugas] (Deadline: [Tanggal])"
        sb.append(no).append(". ")
                .append(t.getDashboardText()) // <-- Panggil method format
                .append("\n");
        no++;
        
      }
    
    if (list.isEmpty()) sb.append("Belum ada tugas.");
    
    jTextAreaTugas.setText(sb.toString());
    jTextAreaTugas.setCaretPosition(0);
}
    
    private void loadPengumumanSimple() {
        pengumumanDAO pDao = new pengumumanDAO();
        List<pengumuman> list = pDao.getPengumumanLengkap();
        
        StringBuilder sb = new StringBuilder();
        int no = 1;
        
        for (pengumuman p : list) {
            // Format: "1. Basis Data - Belajar UAS"
            sb.append(no).append(". ")
              .append(p.getDashboardText()) 
              .append("\n"); 
            no++;
            
        }
        
        if (list.isEmpty()) sb.append("Belum ada pengumuman.");
        
        jTextAreaPengumuman.setText(sb.toString());
        jTextAreaPengumuman.setCaretPosition(0);
    }

}
