
package com.ifobia.form;

import com.formdev.flatlaf.FlatClientProperties;
import com.ifobia.entity_dao.absensiDAO;
import com.ifobia.entity.absensi;
import com.ifobia.entity.user;
import com.ifobia.main.FormMenuUtama;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FormKelolaAbsensi extends javax.swing.JPanel {

    private absensiDAO dao;
    private DefaultTableModel modelInput; // Tabel Atas (jTable1)
    private DefaultTableModel modelRekap; // Tabel Bawah (jTableAbsensi)
    
    private String kodeMkAmpuan = null; 
    private String namaMkAmpuan = null;

    public FormKelolaAbsensi() {
        initComponents();
        jButton1.putClientProperty(FlatClientProperties.STYLE, "background:$Button.custom.background");
        
    //AUTOMATICCCC PENANGGALAN. BUAT MASUK KE LABEL DIATAS TABEL INPUT
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("EEEE, dd MMMM yyyy", new Locale("id", "ID"));
            lblTanggalHariIni.setText(sdf.format(new Date()));
        } catch (Exception e) {}
        
        dao = new absensiDAO();
        
        // MODEL INPUT ITU PAKE TABEL YG ATAS (jTableAbsensi)
        // MODEL REKAP ITU PAKE TABEL YG BAWAH (jTable1)
        modelInput = (DefaultTableModel) jTableAbsensi.getModel(); 
        modelRekap = (DefaultTableModel) jTable1.getModel();       
        
        // LANGSUNG CEK SIAPA YG INOUT ABSEN BASED ON MATKUL APA YG DIA PEGANG 
        cekMatkulPj();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        lblRekap = new javax.swing.JLabel();
        lblInfoMatkul1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAbsensi = new javax.swing.JTable();
        lblTanggalHariIni = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"2410631170170", "SYAHID AHMAD YASIN", null, null, null},
                {"2410631170070", "GERAL TRITAMA WAHYUADY", null, null, null},
                {"2410631170100", "RAIKA MAULANA DWI PUTRA", null, null, null},
                {"2410631170098", "NUGRAHA ADANI", null, null, null}
            },
            new String [] {
                "NIM", "Nama", "Jumlah Pertemuan", "Hadir", "Tidak Hadir"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1186;
        gridBagConstraints.ipady = 193;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 48, 38, 22);
        jPanel1.add(jScrollPane2, gridBagConstraints);

        jButton1.setBackground(new java.awt.Color(13, 71, 161));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 746, 0, 22);
        jPanel1.add(jButton1, gridBagConstraints);

        lblRekap.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        lblRekap.setText("Rekapitulasi Absensi");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 51, 0, 0);
        jPanel1.add(lblRekap, gridBagConstraints);

        lblInfoMatkul1.setFont(new java.awt.Font("Leelawadee", 1, 36)); // NOI18N
        lblInfoMatkul1.setText("Absensi Mata Kuliah");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 51, 0, 0);
        jPanel1.add(lblInfoMatkul1, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Absensi Mata Kuliah");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 51, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        jTableAbsensi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"2410631170170", "SYAHID AHMAD YASIN", null, null},
                {"2410631170070", "GERAL TRITAMA WAHYUADY", null, null},
                {"2410631170100", "RAIKA MAULANA DWI PUTRA", null, null},
                {"2410631170098", "NUGRAHA ADANI", null, null}
            },
            new String [] {
                "NIM", "Nama", "Status", "Keterangan"
            }
        ));
        jScrollPane1.setViewportView(jTableAbsensi);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1183;
        gridBagConstraints.ipady = 178;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 51, 0, 22);
        jPanel1.add(jScrollPane1, gridBagConstraints);

        lblTanggalHariIni.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        lblTanggalHariIni.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTanggalHariIni.setText("Tanggal");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 320;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 480, 0, 22);
        jPanel1.add(lblTanggalHariIni, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    
    private void cekMatkulPj() {
        user pj = FormMenuUtama.getLoggedInUser();
        
        if (pj != null) {
            String[] infoMatkul = dao.getMatkulPJ(pj.getId_user());
            
            if (infoMatkul != null) {
                kodeMkAmpuan = infoMatkul[0]; 
                namaMkAmpuan = infoMatkul[1];
                lblInfoMatkul1.setText(namaMkAmpuan);
                lblRekap.setText("Rekapitulasi Absensi Mata Kuliah " + namaMkAmpuan);
                
                // LOAD DATA
                tampilkanDataInput(); // LOAD INPUT KE TABEL ATAS
                loadTabelRekap();     // LOAD REKAP KE TABEL BWH
            } else {
                lblInfoMatkul1.setText("Anda tidak memiliki Jadwal Ampuan!");
                jButton1.setEnabled(false);
            }
        }
    }
    
    // INPUT HARI INI
    private void tampilkanDataInput() {
        modelInput.setColumnIdentifiers(new Object[]{"ID", "NPM", "Nama Mahasiswa", "Status", "Keterangan"});
        modelInput.setRowCount(0);
        
        List<absensi> daftarMhs = dao.getSemuaMahasiswa();
        
        for (absensi mhs : daftarMhs) {
            modelInput.addRow(new Object[]{
                mhs.getIdUser(), mhs.getNPM(), mhs.getNama(), "Hadir", "-"
            });
        }
        
        // CONIFIGURE TABELL ATAS
        if (jTableAbsensi.getColumnModel().getColumnCount() > 0) {
            jTableAbsensi.getColumnModel().getColumn(0).setMinWidth(0);
            jTableAbsensi.getColumnModel().getColumn(0).setMaxWidth(0);
            jTableAbsensi.getColumnModel().getColumn(0).setWidth(0);

            JComboBox<String> combo = new JComboBox<>(new String[]{"Hadir", "Sakit", "Izin", "Alpha"});
            jTableAbsensi.getColumnModel().getColumn(3).setCellEditor(new DefaultCellEditor(combo));
        }
        jTableAbsensi.setRowHeight(30);
    }

    // TABEL REKAPPPPPPPP
        private void loadTabelRekap() {
            if (kodeMkAmpuan == null) return;

            // 1. Reset Tabel
            modelRekap.setRowCount(0);
            modelRekap.setColumnCount(0); 

            // 2. Buat Header Kolom
            modelRekap.addColumn("Nama Mahasiswa");

            // Ambil daftar tanggal absen yang sudah pernah disimpan
            List<String> listTanggal = dao.getListTanggal(kodeMkAmpuan);

            // Buat kolom P1 s/d P14 (sesuai standar pertemuan)
            int jumlahPertemuan = 14; 
            for (int i = 0; i < jumlahPertemuan; i++) {
                String judul = "P" + (i + 1);
                // Kalau tanggalnya ada, tampilkan tgl/bulan di header
                if (i < listTanggal.size()) {
                    try {
                        String tglFull = listTanggal.get(i);
                        String tglPendek = tglFull.substring(8, 10) + "/" + tglFull.substring(5, 7); // DD/MM
                        judul += " (" + tglPendek + ")";
                    } catch (Exception e) {}
                }
                modelRekap.addColumn(judul);
            }

            // Kolom Total
            modelRekap.addColumn("H"); 
            modelRekap.addColumn("S");
            modelRekap.addColumn("I"); 
            modelRekap.addColumn("A");

            // 3. Isi Data Mahasiswa & Statusnya
            List<absensi> daftarMhs = dao.getSemuaMahasiswa();

            for (absensi mhs : daftarMhs) {
                // Array baris: 1 (Nama) + 14 (Pertemuan) + 4 (Total)
                Object[] rowData = new Object[1 + jumlahPertemuan + 4]; 

                rowData[0] = mhs.getNama(); // Kolom Nama

                int h=0, s=0, iz=0, a=0; // Variabel hitung total

                // Loop per pertemuan
                for (int x = 0; x < jumlahPertemuan; x++) {
                    String kode = "-"; // Default kalau belum absen

                    // Jika pertemuan ke-x sudah terlaksana (ada tanggalnya)
                    if (x < listTanggal.size()) {
                        String tgl = listTanggal.get(x);
                        // Cek status mahasiswa ini di tanggal tersebut
                        String status = dao.getStatusAbsen(kodeMkAmpuan, mhs.getIdUser(), tgl);

                        if (status != null) {
                            if (status.equalsIgnoreCase("Hadir")) { kode = "H"; h++; }
                            else if (status.equalsIgnoreCase("Sakit")) { kode = "S"; s++; }
                            else if (status.equalsIgnoreCase("Izin")) { kode = "I"; iz++; }
                            else if (status.equalsIgnoreCase("Alpha")) { kode = "A"; a++; }
                            else { kode = "?"; }
                        }
                    }
                    rowData[x + 1] = kode;
                }

                // Isi Total di ujung kanan
                rowData[jumlahPertemuan + 1] = h; 
                rowData[jumlahPertemuan + 2] = s;
                rowData[jumlahPertemuan + 3] = iz; 
                rowData[jumlahPertemuan + 4] = a;

                modelRekap.addRow(rowData);
            }
    
    // 4. Rapikan Lebar Kolom
    jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
    jTable1.getColumnModel().getColumn(0).setPreferredWidth(200); // Nama agak lebar
    for(int i=1; i<=jumlahPertemuan; i++) {
        jTable1.getColumnModel().getColumn(i).setPreferredWidth(60); // Kolom P1-P14 kecil
    }
}    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // STOP EDITINGG TABEL
    if (jTableAbsensi.isEditing()) {
        jTableAbsensi.getCellEditor().stopCellEditing();
    }                                     
        if (kodeMkAmpuan == null) return;

        // Stop editing cell jika user masih mengetik/memilih
        if (jTableAbsensi.isEditing()) jTableAbsensi.getCellEditor().stopCellEditing();

        int success = 0;
        int total = modelInput.getRowCount();

        // SIMPAN DATA ABSEN SCR LOOPING
        for (int i = 0; i < total; i++) {
            // Ambil ID dari kolom 0 (Hidden column)
            int idMhs = Integer.parseInt(modelInput.getValueAt(i, 0).toString());
            String status = modelInput.getValueAt(i, 3).toString();
            String ket = modelInput.getValueAt(i, 4).toString();

            // PANGGIL DAO
            if (dao.simpanAbsensi(kodeMkAmpuan, idMhs, status, ket)) {
                success++;
            }
        }

        // MESSAGE STATUS SUKSES MENYIMPAN DATA
        if (success > 0) {
            JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan!");
        } else {
            // Optional: Tetap beri info jika tidak ada perubahan baru
            JOptionPane.showMessageDialog(this, "Data disimpan (Tidak ada data update).");
        }

        loadTabelRekap(); 

        
       
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableAbsensi;
    private javax.swing.JLabel lblInfoMatkul1;
    private javax.swing.JLabel lblRekap;
    private javax.swing.JLabel lblTanggalHariIni;
    // End of variables declaration//GEN-END:variables
}
